// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe-tHN5VOFGclpke00YJ1Q7B0re4T3nAw',
    appId: '1:244181607041:web:02f3786b228ffa66aba380',
    messagingSenderId: '244181607041',
    projectId: 'e-hadir-b42ba',
    authDomain: 'e-hadir-b42ba.firebaseapp.com',
    storageBucket: 'e-hadir-b42ba.firebasestorage.app',
    measurementId: 'G-1CY72599T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd461CVHCfZMQXyIyB_MHOKDThnldecJ0',
    appId: '1:244181607041:android:13aaf191a6cb588faba380',
    messagingSenderId: '244181607041',
    projectId: 'e-hadir-b42ba',
    storageBucket: 'e-hadir-b42ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJxvAr3LOv_NnizT2AtSyvQFOQR30Q90',
    appId: '1:244181607041:ios:e5f3d5bf4f7ecc93aba380',
    messagingSenderId: '244181607041',
    projectId: 'e-hadir-b42ba',
    storageBucket: 'e-hadir-b42ba.firebasestorage.app',
    iosBundleId: 'com.example.eHadir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJxvAr3LOv_NnizT2AtSyvQFOQR30Q90',
    appId: '1:244181607041:ios:e5f3d5bf4f7ecc93aba380',
    messagingSenderId: '244181607041',
    projectId: 'e-hadir-b42ba',
    storageBucket: 'e-hadir-b42ba.firebasestorage.app',
    iosBundleId: 'com.example.eHadir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe-tHN5VOFGclpke00YJ1Q7B0re4T3nAw',
    appId: '1:244181607041:web:5ceffd426039aa0faba380',
    messagingSenderId: '244181607041',
    projectId: 'e-hadir-b42ba',
    authDomain: 'e-hadir-b42ba.firebaseapp.com',
    storageBucket: 'e-hadir-b42ba.firebasestorage.app',
    measurementId: 'G-68Y6C98VFR',
  );
}
